pipeline {
    agent any

    environment {
        SERVER_IP = credentials('prod-server-ip')
    }

    stages {
        stage('Test') {
            steps {
                sh '''
                    python3 -m venv venv
                    ./venv/bin/pip install -r requirements.txt
                    ./venv/bin/pytest
                '''
            }
        }

        stage('Package code') {
            steps {
                sh 'zip -r myapp.zip ./* -x "*.git*"'
                sh 'ls -lart'
            }
        }

        stage('Deploy to Prod') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'ssh-key', keyFileVariable: 'MY_SSH_KEY', usernameVariable: 'username')]) {
                    sh '''
                        scp -i $MY_SSH_KEY -o StrictHostKeyChecking=no myapp.zip ${username}@${SERVER_IP}:/home/${username}/
                        ssh -i $MY_SSH_KEY -o StrictHostKeyChecking=no ${username}@${SERVER_IP} << EOF
                            unzip -o /home/${username}/myapp.zip -d /home/${username}/app/
                            /home/${username}/app/venv/bin/pip install -r /home/${username}/app/requirements.txt
                            sudo systemctl restart flaskapp.service
EOF
                    '''
                }
            }
        }
    }
}
