pipeline {
    agent any

    environment {
        IMAGE_NAME = 'shoshoavi/jenkins-flask-app'
        IMAGE_TAG = "${IMAGE_NAME}:${env.GIT_COMMIT}"
        VENV_DIR = 'jenkins-python-dir/venv'
    }

    stages {

        stage('Setup Virtual Env') {
            steps {
                dir('04-docker') {
                    sh '''
                        python3 -m venv ${VENV_DIR}
                        . ${VENV_DIR}/bin/activate
                        pip install --upgrade pip
                        pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Test') {
            steps {
                dir('04-docker') {
                    sh '''
                        . ${VENV_DIR}/bin/activate
                        pytest
                    '''
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                dir('04-docker') {
                    withCredentials([usernamePassword(credentialsId: 'docker-creds', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                        sh 'echo ${PASSWORD} | docker login -u ${USERNAME} --password-stdin'
                        echo 'Login successfully'
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('04-docker') {
                    sh 'docker build -t ${IMAGE_TAG} .'
                    echo "Docker image built successfully"
                    sh 'docker image ls'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                dir('04-docker') {
                    sh 'docker push ${IMAGE_TAG}'
                    echo "Docker image pushed successfully"
                }
            }
        }
    }
}
